<?php

namespace Scrumator\Bundle\BackendBundle\Entity;

/**
 * CiviliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CiviliteRepository extends \Doctrine\ORM\EntityRepository
{
}
