<?php

namespace Scrumator\Bundle\BackendBundle\Entity;

/**
 * PointsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByPoints(){
        return $this->getEntityManager()
                ->createQuery(
                        'SELECT p FROM ScrumatorBackendBundle:Points p ORDER BY p.number'
                        )
                ->getResult();
    }
}
