<?php

namespace Scrumator\Bundle\BackendBundle\Entity;

/**
 * SprintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SprintRepository extends \Doctrine\ORM\EntityRepository
{
}
