<?php

namespace Scrumator\Bundle\BackendBundle\Entity;

/**
 * Sprint_paramsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sprint_paramsRepository extends \Doctrine\ORM\EntityRepository
{
}
