<?php

namespace Scrumator\Bundle\BackendBundle\Entity;

/**
 * User_storiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User_storiesRepository extends \Doctrine\ORM\EntityRepository
{
}
