<?php

namespace Scrumator\Bundle\BackendBundle\Entity;

/**
 * User_storiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User_storiesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOne($id) {
        
        $qb = $this->createQueryBuilder('u')
                ->join("u.project", "p")
                ->where('u.id=:id')
                ->setParameter('id', $id);
                
        
        return $qb->getQuery()->getResult();
    }
}
