<?php

namespace Scrumator\Bundle\BackendBundle\Entity;

/**
 * User_statusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User_statusRepository extends \Doctrine\ORM\EntityRepository
{
}
